kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/even.wanvik@dfo.no/Workspaces/RD-dataplatform-etl/dags
        containerPath: /mnt/airflow/dags
      - hostPath: /home/even.wanvik@dfo.no/Workspaces/RD-dataplatform-etl/logs
        containerPath: /mnt/airflow/logs